//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities3 : DbContext
    {
        public dbEntities3()
            : base("name=dbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<biodata> biodatas { get; set; }
        public virtual DbSet<business> businesses { get; set; }
        public virtual DbSet<lga> lgas { get; set; }
        public virtual DbSet<personal> personals { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
    }
}
