//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craps.Models
{
  using Newtonsoft.Json;
  using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int business_id { get; set; }
        public Nullable<int> biodata_id { get; set; }
        public string business_name { get; set; }
        public string reg_number { get; set; }
        public string directors { get; set; }
        public string business_email { get; set; }

    [JsonIgnore]
    public virtual biodata biodata { get; set; }
    }
}
