//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lga
    {
        public int lga_id { get; set; }
        public string lga_state { get; set; }
        public string lga_area { get; set; }
    }
}
