//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craps.Models
{
  using Newtonsoft.Json;
  using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int personal_id { get; set; }
        public Nullable<int> biodata_id { get; set; }
        public string selfie_file { get; set; }
        public byte[] selfie_data { get; set; }
        public string sign_file { get; set; }
        public byte[] sign_data { get; set; }

    [JsonIgnore]
    public virtual biodata biodata { get; set; }
    }
}
