//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int tran_id { get; set; }
        public string tran_ref { get; set; }
        public System.DateTime tran_date { get; set; }
        public string tran_status { get; set; }
        public double tran_amount { get; set; }
    }
}
